### ISSUE TITLE
Icons on notifications need more contrast

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#121]
This is how it looks:
![bildschirmfoto von 2018-04-19 06-15-46](https://user-images.githubusercontent.com/36449926/39084596-a34ec1b8-4578-11e8-8d3b-cd6cf4128c1b.png)

It would be better when the icons get darker to increase visibility on first sight. Black?:
![dropboxblack](https://user-images.githubusercontent.com/36449926/39084605-bf5bdc6a-4578-11e8-8445-c1149760a6a4.png)

**Comment by Feichtmeier** [comment]
I'll check if the icon has the same color as the text and maybe darken both a bit. Pure black does not look that good though

**Comment by NusiNusi** [comment]
If the color of the icon can be changed independent from textcolor, could you show us how it would look like with orange icons? i made a bad mockup here and explained why it would be worth thinking about: https://github.com/ubuntu/gtk-communitheme/issues/289

**Comment by clobrano** [comment]
Please, let's keep in mind the meaning of orange in our palette. It is used as a selection color. I agree with @Feichtmeier on trying to make it more visibile, but not with orange

**Comment by Feichtmeier** [comment]
Hmmmm. I just noticed that I need to change this somewhere else but the notification code.
Since other icons are for example colorful, like a chrome notification:

![screenshot from 2018-04-23 16-31-13](https://user-images.githubusercontent.com/15329494/39133273-1ae05894-4714-11e8-9c22-9c6985851d81.png)

**Comment by NusiNusi** [comment]
@Feichtmeier @clobrano 
since the other ticket is going to be closed i post my bad mockup here. this is how it could look with orange icons:
![dropbox](https://user-images.githubusercontent.com/36449926/39151322-31a39628-4745-11e8-86da-30f5c0759736.png)
It can be branding or warning. If this is a no-go, then lets forget about it and try to darken them up if possible.

**Comment by clobrano** [comment]
Thank you @Feichtmeier to test this, but I stick on my opinion

**Comment by Feichtmeier** [comment]
@clobrano  @NusiNusi I think this is how it works:

If there is an symbolic icon for the app which spits notifications the symbolic icon is used
Otherwise there is a fallback to the regular app icon, like in the chrome example above (that was the reason I showed you that screenshot)

I didn't have time to look up the code where the color of the symbolic icon is defined but orange makes absolutely no sense to me and it does not look very beautiful or in my opinion. 
For me an orange Icon is yet something different than for example and orange underline. An orange icon means WARNING for me. It's almost like an error. But if you receive an email notification or from telegram it should not have that feeling. It should be something subtile yet recognizeable.

**Comment by NusiNusi** [comment]
Same color for icon and text +1

**Comment by Feichtmeier** [comment]
@godlyranchdressing I fixed the border bleed as you know ;O but I could not fix the icon color to match the text color. Could you give it a try please?

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/gnome-shell-communitheme/pull/166
