### ISSUE TITLE
No ubuntu on communitheme option with snap.

### ISSUE THREAD

**Issue by patonoide** [ubuntu/gnome-shell-communitheme#129]
So for some reason there is no option to select communitheme on lightdm or gdm when using the snap version, but if I use the ppa it works fine. I am using Ubuntu 17.10.

**Comment by Feichtmeier** [comment]
It only works on 18.04, sorry : /

"The session is thus installed by default on your 18.04 system, but only reveals (thanks to TryExec) once you install the snap! Due to all this, the snap will consequently only work on 18.04 LTS as we need those changes in the distribution and some of them are tailored to Communitheme. We hope to generalize those patches in the future."
Taken from 
https://didrocks.fr/2018/04/10/welcome-to-the-ubuntu-bionic-age-new-wip-ubuntu-theme-as-a-snap/
