### ISSUE TITLE
Finetune Ubuntu-button when clicked

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#134]
![peek 2018-04-26 20-56](https://user-images.githubusercontent.com/36449926/39326220-94675b0e-4994-11e8-88fa-1c427625f4cc.gif)

@madsrh @Feichtmeier 
Other Icons in the dock get an orange dot. What happens to the ubuntu-button feels somehow boring.

Possible solutions:
1. Give the gray background an orange border when clicked

2. Make the logo orange when clicked

3. I have a better idea...

4. Close this. Not interested.

**Comment by godlyranchdressing** [comment]
The Ubuntu icon acting as the button will probably be scrapped since it's too different from documentation/upstream Adwaita. @didrocks loves to mention it every now and then :laughing: but maybe this is the best time to talk about how it should look when it's the usual app-grid icon though. I was thinking to just have a semi-transparent background so the icon doesn't get lost against a light wallpaper.

![screenshot from 2018-04-26 15-33-45](https://user-images.githubusercontent.com/27529229/39327893-7099ec96-4967-11e8-91c6-7ec1a2d48119.png)
![screenshot from 2018-04-26 15-33-42](https://user-images.githubusercontent.com/27529229/39327894-70b3ea92-4967-11e8-8146-201fdf21365a.png)

**Comment by Feichtmeier** [comment]
How about spreading the grid when pressed? Would need a second icon ofc

**Comment by Ads20000** [comment]
> How about spreading the grid when pressed?

Maybe if people agree with that suggestion then that should be filed as an Issue or PR against upstream GNOME Shell since it applies to them too? Would be good to see if they accept it or their reasons for rejecting before the Communitheme deviates there.

> Other than that the background change is nice

Maybe... Not sure, I thought @NusiNusi 's usual complaint is that there's too much orange?! But having an orange border here would create more orange?

**Comment by madsrh** [comment]
I would say **+1** for following upstream, but I have to admit that my initial thought was to turn orange when pressed like [here](http://www.phoronix.net/image.php?id=zesty-unity8-mir&image=ubuntu1704_unity8_5_show), but that wouldn't be very consistent with the rest of the theme.

**Comment by NusiNusi** [comment]
@Ads20000 

> Maybe... Not sure, I thought @NusiNusi 's usual complaint is that there's too much orange?! But having an orange border here would create more orange?

Now you are trolling.

@madsrh making it orange would fit to the rest of the themes logic: "active" / "selected" = orange
Can we test this?

**Comment by godlyranchdressing** [comment]
As in the grid color becomes orange?

**Comment by madsrh** [comment]
@godlyranchdressing are you asking Ghost? 👻 I guess, he meant the background.

**Comment by Feichtmeier** [comment]
Closing this as the discussion is more about grid or ubuntu logo for now and I will cover this discussion once I "migrated" the issues to the gtk repo
