### ISSUE TITLE
Theme does not work if an app run with sudo

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gnome-shell-communitheme#152]
Ubuntu 18.04 fresh install but I kept `/home` partition so maybe my problems are because of that.
Anyway if I run Synaptic or for example Nautilus with `sudo` I get missing icons and not-really-communitheme look. 
I'm attaching screenshot with my settings and 2 Nautilus windows, the bottom one was started with `sudo`
![zrzut ekranu z 2018-05-01 12-20-28](https://user-images.githubusercontent.com/1629120/39471419-03cbb7f2-4d3b-11e8-913b-96fef36f4138.png)

**Comment by Feichtmeier** [comment]
This is a won't fix as far as I understood @didrocks correctly.
S

**Comment by Ads20000** [comment]
I can't find a better link but for loading graphical applications[ it's recommended you use the gvfs admin backend to launch applications as root](https://bugs.launchpad.net/ubuntu/+source/umit/+bug/1740618) rather than using sudo. You can do this with the `admin://` prefix. E.g. `nautilus admin:///home/`

**Comment by Feichtmeier** [comment]
@Ads20000 thanks for clarification I think that was what didi suggested in the other issues about this
