### ISSUE TITLE
Popup-Sub-Menus border colors aren't identical

### ISSUE THREAD

**Issue by madsrh** [ubuntu/gnome-shell-communitheme#231]
We had a long discussion about the popup-submenu border colors. IMO we should return to **two identical lines**, because the current coloring doesn't give that 3D effect that we (mostly me) was aiming for 🤷‍♂️ and therefore makes it look like it a mistake.

Current coloring:
![image](https://user-images.githubusercontent.com/3986894/42294813-5d1ae612-7fe4-11e8-9585-2b4af8eb6420.png)

**Comment by Feichtmeier** [comment]
Wrong repo Mads :P

**Comment by madsrh** [comment]
WTF? Isn't this a menu that drops down from the Gnome shell top panel??? How can that not be part of the 🐚😣

Sorry about that, I'm lost!

**Comment by Feichtmeier** [comment]
Haha! xD it would be the correct repo. But @didrocks will change this and the shell theme code will be merged in the Gtk repo. That's the reason I've migrated all the issues

**Comment by Feichtmeier** [comment]
Oh oh.... 

We have to elements here:
1) the "checked" element which you click to open the sub menu
2) the submenu

Both can either have border colors OR ONE (yes only one!) box-shadow or they can have and/or a border-top/bottom.

Soooo the only solution to have the same border thickness on top and bottom of the submenu is to use a bordertop and bottom. But.... then this effect appears:

![peek 2018-07-08 19-44](https://user-images.githubusercontent.com/15329494/42422490-4821f6fa-82e7-11e8-98c2-f8de714f9c28.gif)

**Comment by madsrh** [comment]
> ... the only solution to have the same border thickness...

Do you mean the color? I only wanted to change the border color.

It's a very minor issue, so shouldn't we just leave it as it is?

**Comment by Feichtmeier** [comment]
Yes I meant the color sorry. Somehow the same color looks different on border and box Shadow. But good idea, I try to have two separate colours and see if this fixes the missmatch

**Comment by Feichtmeier** [comment]
![peek 2018-07-09 12-09](https://user-images.githubusercontent.com/15329494/42444672-fc9744ee-8370-11e8-8469-ce73e02b47c0.gif)

Ha yes indeed you are a genius! 
Border colors are transparentize($fg_color, 0.91);
This is somehow darkened by the checked element. So I transparentized the box-shadow a bit less on the checked element and tadah:

![peek 2018-07-09 12-09](https://user-images.githubusercontent.com/15329494/42444898-a7d8eede-8371-11e8-9ff5-64a9906e8045.gif)

I am not sure... is that line poppping effect worse or better in this version? Otherwise there would be no difference in either taking the border or the box-shadow :man_shrugging:

**Comment by madsrh** [comment]
@Feichtmeier Ahhh, that's perfect 👍 

> is that line poppping effect worse or better in this version?

Hard to tell from the gif. You pick one 😉
