### ISSUE TITLE
Follow button design rules on dark

### ISSUE THREAD

**Issue by Luxamman** [ubuntu/gnome-shell-communitheme#44]
- Only buttons when clicked or permanent clicked have inner-shadow
- Focus is always a surrounding orange line (should be present everywhere in the system)
- Connected buttons and breadcrumbs and similar have a grey back, selected areas/folders have a bottom orange line for feedback/orientation. The inner shadow could make (visual) problems I guess in some circumstances, so I suggest simple flat design. And they have a padding or background color border between to look separated.

![aa60ec53b6454bc457914e8a20a8ff65e068cdbe](https://user-images.githubusercontent.com/20417555/35669144-7379175e-0734-11e8-9bce-69e426d859d7.png)
![b2](https://user-images.githubusercontent.com/20417555/35669147-74e31d2e-0734-11e8-80b0-0a14004a357a.png)
![b3](https://user-images.githubusercontent.com/20417555/35669149-761e1ff4-0734-11e8-8eea-62e753114a22.png)
![b4](https://user-images.githubusercontent.com/20417555/35669150-775ebbc6-0734-11e8-9145-594134cf8be7.png)

**Comment by ya-d** [comment]
Dark system dialogues currently darken the selected button instead of using an orange border.

Also see https://github.com/Ubuntu/gtk-communitheme/issues/160 for consistency in use of vertical separators.

<img width="570" alt="dark button selction" src="https://user-images.githubusercontent.com/30781876/36109539-011481b8-1020-11e8-942f-008cfb9a6a9a.png">
