### ISSUE TITLE
"communitheme" name is misleading since "communitheme" apparently is not lead by the community

### ISSUE THREAD

**Issue by kq01526** [Ubuntu/gnome-shell-communitheme#57]
Public posting on the forum is disabled, see: https://community.ubuntu.com/t/about-the-theme-refresh-category/1897

And the GitHub issue tracker is being censored, see: https://github.com/Ubuntu/gnome-shell-communitheme/issues/54

Should this theme really be called "communitheme" then?

**Comment by madsrh** [comment]
Did you read [this thread](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/)?

What is being censored? You can see all the code, suggestions and discussions, and if you want submit a PR.

**Comment by kq01526** [comment]
>  @madsrh wrote:
> What is being censored?

The issue tracker.

@galgalesh immediately closed my request and marked the discussion as "too heated" just because I pointed out the obvious whereas others clearly did ignore facts while trying to tell me I am seeing things.

But before doing that, @galgalesh made sure to edit [my initial request](https://github.com/Ubuntu/gnome-shell-communitheme/issues/54#issue-296570243) to something entirely different without even asking me first. I had requested aubergine, he simply changed it to Suru blue. I had requested aubergine folder icons. He simply removed any mention of folder icons from the initial post. I had aubergine in the title. He just changed it to what he wants, without asking me for my consent.

> @madsrh wrote:
> Did you read [this thread](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/)?

No. Thanks.

**Comment by madsrh** [comment]
Okay, you might get a better understanding of everything if you read the thread.

Changing the color of the folder icons, is a discussion for the Suru icon theme, but I see that you've already opened an issue there.
I'm sure there was a misunderstanding with the renaming. Sometimes discussions takes new directions and the title should reflect that.

I don't want to start the discussion again, but I believe that this was what they were referring to:
![colors](https://user-images.githubusercontent.com/3986894/36336640-ed6bec10-1389-11e8-96b3-16ec9d95e996.jpg)

**Comment by galgalesh** [comment]
I'm sorry for changing your original issue from Purple to Suru blue, I thought that was what you meant. I was trying to get the discussion back on track.

However, you could've just politely said that you explicitly meant the aubergine instead of the Suru blue and change the issue back.

Instead you continued being disrespectful and mocking the designer. It doesn't matter what the content is of what you're saying. If you can't bring your arguments in a respectful manner, then you should not participate in the discussion.

As the "reason" says, the issue wasn't locked because it was invalid or because we don't agree with you or anything, it was locked because of the tone of the conversation.

**Comment by kq01526** [comment]
> @galgalesh wrote:
> Suru blue, I thought that was what you meant

I meant aubergine. Because it is part of the Ubuntu theming/branding.

Yet both you as well as @Luxamman basically repeatedly told me I am hallucinating and told me that aubergine was never part of Ubuntu, which is just not true, which is very discouraging.

If several people tell you that you are "lying", even though it's them who are not telling the truth, it makes it hard to stay serious.

That being said: I think blue is better suited for theming than aubergine. However: Blue has never been part of Ubuntu theming, whereas aubergine is (feel free to prove me wrong with actual screenshots).

Otherwise I would have requested blue. But again, if you ask me, blue does not fit Ubuntu theming/branding at all. So I am pretty surprised that you guys are arguing it would fit better than aubergine (and at the same time argue that orange needs to stay because it's part of Ubuntu theming/branding).

**Comment by galgalesh** [comment]
Again, regardless of how "right" you think you are, being disrespectful is not ok. We're all humans, we're all giving up our free time to give you a better theme, we all deserve to be treated with respect. If something we say offends you or if you feel mistreated, don't let your emotions guide you. Just take a break, come back after a few days and respectfully let us know what the issue is. English is a second language for most of the people here, so it's a lot more likely that something gets misinterpreted than that someone actually meant to hurt you.

The [Ubuntu code of conduct](https://www.ubuntu.com/about/about-ubuntu/conduct) has some good advice on this.

> Ubuntu is about showing humanity to one another: the word itself captures the spirit of being human.
> 
> Disagreement is no excuse for poor manners. We work together to resolve conflict, **assume good intentions** and do our best to act in an empathic fashion. We don't allow frustration to turn into a personal attack. A community where people feel uncomfortable or threatened is not a productive one.

If you want to contribute something to Ubuntu, if you think your opinions are valuable, then share them respectfully. Otherwise people will just stop listening to you and the only effect you'll have is that the person at the other end of the conversation will have a shit day.



---------------------------------------------------------

You explain what you took offence to:

> Yet both you as well as @Luxamman basically repeatedly told me I am hallucinating and told me that aubergine was never part of Ubuntu, which is just not true, which is very discouraging.

> If several people tell you that you are "lying", even though it's them who are not telling the truth, it makes it hard to stay serious.

You're probably referring to this comment by Luxamman:

> Aubergine has no meaning in the UX because it's never been used and the user is therefore not used to it.

This refers to Aubergine having no **semantic** meaning. Users don't associate a meaning with aubergine because it has never been used to mean something, it has only been used as a branding color, as he further explained.

> This is a background of the start loading screen (and the terminal) and this has no further meaning **for UX**.

This is why it is part of the ["branding" color palette](https://design.ubuntu.com/brand/colour-palette/), but not part of the [SDK color palette](https://docs.google.com/presentation/d/1FtHFW67ycl6uvxZqKIZwyinVyOuV9NxXDuJv1SwQ70k/edit#slide=id.g13b3c671fc_1_0). [It has been removed from the SDK color palette in 2016](https://design.canonical.com/2016/05/colour-palette-updates/) when they made the move to a  "meaningful" and "functional" color scheme.

The designer further explains:

> In previous colour palettes we have included aubergine. However to keep the palette as functional as possible we’ve removed it from this revision. It’s a brand colour and we’ve found it struggles when used in a utility context. You can see the proposed usage of the aubergine in our design guidelines. We’re in the process of updating our app guidelines to reflect this.

We also said that aubergine is the color of the Canonical brand, not the Ubuntu brand. Ubuntu brand color is orange, Canonical brand color is aubergine.

![image](https://user-images.githubusercontent.com/1492981/36345760-4a0b1886-1431-11e8-827e-8662f3d4b77d.png)

http://ubuntu.com vs http://canonical.com also clearly shows the orange vs aubergine brand color. Although granted, The title of "supporting color for consumer and enterprise communications" is broad enough that it can also apply to Ubuntu. So as Luxaman stated

> This is not excluding it, but also doesn't favor it

**in conclusion**

We never meant to say you were lying, we simply tried to explain exactly what I just did, but in a lot les words. I've been writing this response for over an hour in order to make it as clear as possible, it's hard and time-consuming to explain stuff clearly.

-----------------------------------------------------------------------

This is the kind of stuff that is easy to clear out if you stay respectful but it will blow up if you let your emotions guide you. We respectfully disagreed, but in the heat of the moment your brain turned that into "hallucinating" and "lying".

We all put _a lot_ of effort into replying to you both here and in the other thread, so I really hope this isn't wasted time for us. At the very least, I hope that you take this advice to make more positive contributions to Ubuntu.

**Comment by kq01526** [comment]
FYI:

https://github.com/Ubuntu/gtk-communitheme/issues/29#issuecomment-366788891

:grin:
