### ISSUE TITLE
gtk2-engines-pixbuf to be a dependency?

### ISSUE THREAD

**Issue by clobrano** [ubuntu/gnome-shell-communitheme#61]
According to this discussion https://github.com/Ubuntu/gtk-communitheme/issues/112, without gtk2-engines-pixbuf gtk2 applications show some (more) glitches.

@didrocks do you think this should be a dependency for communitheme-session or the issue and the fix should be reported elsewhere?

**Comment by didrocks** [comment]
`gtk2-engines-pixbuf` is in universe, which means it's a component we don't support right now and can't depend on it. 

Our current GTK2 Ambiance theme doesn't require it, do you know exactly why it's needed?

If so, we will need to find a MIR (Main Inclusion Request) + security review to ensure we can support it, then we can have the GTK2 theme package depend on it. (This is a long process, so we need to know exactly why it's required, while our current Ambiance theme doesn't. I bet it's because the assets are svg?).

**Comment by nana-4** [comment]
GTK2 theming depends on (GTK2) theme engines.

Ambiance uses only ["murrine" engine](https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/view/head:/Ambiance/gtk-2.0/gtkrc#L99), but Communitheme and upstream Adwaita use ["pixmap" engine](https://github.com/Ubuntu/gtk-communitheme/blob/master/Communitheme/gtk-2.0/main.rc#L141) and ["adwaita" engine](https://github.com/Ubuntu/gtk-communitheme/blob/master/Communitheme/gtk-2.0/main.rc#L139).

So I suggest that [`gnome-themes-standard`](https://packages.ubuntu.com/bionic/gnome-themes-standard) will be a dependency instead of `gtk2-engines-pixbuf` because the package contains the Adwaita theme engine and also depends on `gtk2-engines-pixbuf`.

**Comment by didrocks** [comment]
Well, that doesn't change the main issue: depending on a component in universe, which is going to be a blocker for seeding it by default. Also, I don't see why we would depend on `gnome-themes-standards` without using the adwaita engine, or do you mean that Communitheme is really depending on the `adwaita` engine (and not pixbuf directly) and thus, both should be seeded?

It would mean thus 2 MIRs.

**Comment by nana-4** [comment]
I may caused a misunderstanding, sorry.

I mean that GTK2 Communitheme is depending on **2 theme engines**, "[adwaita](https://gitlab.gnome.org/GNOME/gnome-themes-extra/blob/master/themes/Adwaita/gtk-2.0/adwaita_engine.c)" (in `gnome-themes-standard` package) and "pixmap" (in `gtk2-engines-pixbuf` package).

And, yes. That means 2 MIRs.

**Comment by didrocks** [comment]
Thanks for clarifying @nana-4 :)

Last question to ensure we do the right thing. I thought our GTK2 theme was derived from adwaita (in `gnome-theme-standard`) as you told. However, this package **Recommends** and not **Depends** on  `gtk2-engines-pixbuf`. Do you know why?

Basically:
* What do people miss when they install Adwaita for GTK2 without the pixbuf engine?
* And similarly, what would people miss installing the gtk2 communitheme with the adwaita engine, but without the pixbuf one?

For reference, no symbol from the pixbuf engine used in libadwaita:
```
$ ldd /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libadwaita.so
	linux-vdso.so.1 =>  (0x00007ffed936d000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fd562664000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007fd5623af000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fd56209e000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd561e4a000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd561b36000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd561917000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd561537000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd561333000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fd561126000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd560ded000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd560be7000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fd5609c1000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fd56079d000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fd560402000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fd5601ec000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fd55ff9e000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fd55fd5b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd55fa05000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fd55f7fb000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fd55f5f8000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fd55f3e8000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fd55f1dd000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fd55efd3000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fd55edd0000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fd55ebcd000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd55e9bb000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fd55e715000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fd55e462000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fd55e230000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fd55e02d000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fd55de20000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd55dbf9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd55d9dc000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd55d7d4000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fd55d5cc000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd55d35a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd562ea9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd55d156000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd55cf2e000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd55cd14000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fd55cac2000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fd55c82e000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fd55c625000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd55c3fa000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd55c1f6000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd55bff0000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fd55bda6000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fd55bb79000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fd55b972000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fd55b75d000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fd55b558000)
```

**Comment by nana-4** [comment]
> this package Recommends and not Depends on gtk2-engines-pixbuf. Do you know why?

The package ["recommends" in artful](https://packages.ubuntu.com/artful/gnome-themes-standard), but  ["depends" in bionic](https://packages.ubuntu.com/bionic/gnome-themes-standard).

I don't know exactly why, but `gnome-themes-standard` also contains ["HighContrast" theme which doesn't use "pixmap" engine](https://gitlab.gnome.org/GNOME/gnome-themes-extra/blob/master/themes/HighContrast/gtk-2.0/gtkrc). I guess the reason why `gtk2-engines-pixbuf` was "recommends" is because it's for installing only HighContrast theme (without installing Adwaita theme).

> What do people miss when they install Adwaita for GTK2 without the pixbuf engine?
> And similarly, what would people miss installing the gtk2 communitheme with the adwaita engine, but without the pixbuf one?

PNG assets (in [Adwaita](https://gitlab.gnome.org/GNOME/gnome-themes-extra/tree/master/themes/Adwaita/gtk-2.0/assets), in [Communitheme](https://github.com/Ubuntu/gtk-communitheme/tree/master/Communitheme/gtk-2.0/assets)) cannot be used without the pixmap/pixbuf engine. Thus GTK2 widgets would [look like win95](https://github.com/Ubuntu/gtk-communitheme/issues/112). See [here](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine) for details about pixmap engine.

**Comment by didrocks** [comment]
That sounds good to me! Thanks for looking at it (I hadn't the time to do this whole analyze) and for keeping up with my question ;)

Ok, let's add the deps here (will do a PR this afternoon) and keep in mind we'll need the MIR. It's another argument it's going to be tight for 18.04 though, but I have ideas on how people can easily test the theme even on bionic while keeping up with latest development but shhhhh ;)

**Comment by didrocks** [comment]
FYI, it's reflected as https://github.com/Ubuntu/gtk-communitheme/pull/219.

**Comment by clobrano** [comment]
Closing as per https://github.com/ubuntu/gnome-shell-communitheme/issues/61#issuecomment-369909823
