### ISSUE TITLE
Some appindicators aren't interactive

### ISSUE THREAD

**Issue by Astrowatt** [ubuntu/gnome-shell-communitheme#95]
Hard edit from @Feichtmeier:

--> most Appindiactors show up but are not interactive and the shell popover are not displayed on click

This is what it looks like of late:
![schermafdruk van 2018-04-04 22-47-43](https://user-images.githubusercontent.com/29024246/38334035-8d8e7088-385a-11e8-9101-51901162f474.png)

___________

These are the indicators that are interactive in the communitheme session:
- insync
- google chrome
- telegram
- discord

These are the indicators that are not interactive in the communitheme session:
- dropbox
- Tomboy
- Diodon

App indicators that do not show up at all in the communitheme session:
- skype

___________

 @Astrowatt the wrong icon is actually an icon issue so maybe you can open a good issue on the suru repo? He is willing to include icons IF  the third party is 100% okay with it and brings their own icons to the repo, maybe you can mail dropbox for this? Would be great since we got a lot of other issues to fix

**Comment by clobrano** [comment]
I noticed that too lately

**Comment by Feichtmeier** [comment]
Is that really a communitytheme issue? I wasn't on ubuntu session for a long time but when I was the last time this issue was also there. You can fix it with:

dropbox stop && env XDG_CURRENT_DESKTOP=Unity dropbox start -i

Could you double check if this is really specific for this theme? I  very unsure about that

**Comment by Feichtmeier** [comment]
@clobrano change Inherits=ubuntu-mono-dark in /usr/share/icons/Suru/index.theme

**Comment by clobrano** [comment]
@Feichtmeier great! It might not be alone. Zeal icon looks too big

**Comment by Astrowatt** [comment]
Thanks for the quick reply @Feichtmeier and @clobrano 
I have double-checked, and notice the following.
In a regular Ubuntu Session, the Dropbox icon is monochrone and fully functional, but not scalable:
![schermafdruk van 2018-04-05 08-49-47](https://user-images.githubusercontent.com/29024246/38351588-70d15536-38b0-11e8-8388-24590217ecfd.png)
When I change the icons to Suru, in the Ubuntu session, the Dropbox icon changes into the old one, but is still functional:
![schermafdruk van 2018-04-05 09-01-24](https://user-images.githubusercontent.com/29024246/38351686-e96d2db2-38b0-11e8-8f89-ff2b2f75ec60.png)
Logging into the Communitheme SESSION is where the problem lies. The icon is the old one, is not scalable, and not functional:
![schermafdruk van 2018-04-05 08-50-48](https://user-images.githubusercontent.com/29024246/38351725-12c78a22-38b1-11e8-88fc-d47643ba27e2.png)
With your workaround, @Feichtmeier , Dropbox restarts, becomes scaled and becomes functional. It still is the old icon though:
![schermafdruk van 2018-04-05 08-52-36](https://user-images.githubusercontent.com/29024246/38351748-32733dc6-38b1-11e8-9bc4-f700f91719f0.png)
Logging off and back on makes the problem reappear.

**Comment by Feichtmeier** [comment]
Thanks for the double check. I guess this is somehow related to the environment variable in the communitheme session.

**Comment by galgalesh** [comment]
I submitted an issue for the icon itself upstream: https://github.com/snwh/suru-icon-theme/issues/37

The click behavior is fixed in the PR, although I'd like didrocks' opinion on this before I merge it, since we're basically "lying". Dropbox doesn't understand "we're the `ubuntu-communitheme` session which is _like_ the `ubuntu:gnome` session" so with that pr we now just say "we're the `ubuntu:gnome` session".

**Comment by Feichtmeier** [comment]
Since the PR got deleted, should we close this issue here since the click part is actually a dropbox problem? @galgalesh

**Comment by galgalesh** [comment]
I would leave it open so people don't re-report it, however it needs to be reported to dropbox. I haven't found where to do that exactly. Anyone have a clue?

**Comment by Feichtmeier** [comment]
@galgalesh I once opened an issue exactly for this problem after ubuntu switched to gnome in 17.10 here:
https://dropbox.zendesk.com/hc/de/requests/7111039
The ticket is listed as fixed now, I would try to reopen this but I did not understand what @didrocks said in the PR xD 
How should we argue that we need dropbox adapt to two different themes? I don't think they want to make this

**Comment by didrocks** [comment]
Basically, those things should be fixed in upstream source code to do a string submatch. This is either directly in upstream source code or for electron applications in the electron code itself.

We can't change our `communitheme:ubuntu:GNOME ` or the dedicated communitheme session won't work (the gsettings key override will have no way to differentiate the default session with `ubuntu:GNOME` selecting the Ambiance theme, icon, sound and so on, from the communitheme session).

**Comment by febcrash** [comment]
@galgalesh 
Same issue with Tomboy and Diodon applets

[
![capture d ecran de 2018-05-02 10-02-43](https://user-images.githubusercontent.com/5707986/39512113-fc02f2be-4def-11e8-9945-d6848ad7fe7e.png)
](url)
See https://github.com/snwh/suru-icon-theme/issues/21

**Comment by Feichtmeier** [comment]
@didrocks since more than only dropbox are affected, do you have any idea how we could bring up a solution from our side? I fear we would not make it to 18.10 to contact every possible third party app that has a working indicator in ubuntu session but not in communitheme session  :( Sorry for the noise but this is really bugging me since I rely on some indicators myself in my daily work

**Comment by fenris** [comment]
- slack desktop

**Comment by clobrano** [comment]
Thanks for reporting, but we understood the problem and we're waiting for upstream to accept @didrocks's solution, so no need to add more application

**Comment by fenris** [comment]
ok noted .. where can i view the status of @didrocks solution at upstream? are they(upstream) accepting it?

**Comment by Feichtmeier** [comment]
I just tried to contact dropbox again for the substring search. I hope they respond. I linked this issue here.

**Comment by Feichtmeier** [comment]
Yup discord works now<3 Thank you @didrocks 
I got mail from  dropbox, too - but only a "we will get back to you mail", but my hopes are strong in dropbox! :)
![screenshot from 2018-05-23 14-04-09](https://user-images.githubusercontent.com/15329494/40423346-88b891b6-5e92-11e8-864d-f1fea8fa6882.png)

**Comment by Feichtmeier** [comment]
Dropbox said they will fix this soon Oo oO no idea what that means

**Comment by Feichtmeier** [comment]
Migrated to the gtk repo -> closing this
