### ISSUE TITLE
Slider Inconsistencies

### ISSUE THREAD

**Issue by pojntfx** [ubuntu/gnome-shell-communitheme#98]
Just noticed that the sliders in the GNOME Shell theme and the GTK theme look quite different:

![screenshot from 2018-04-06 00-50-05](https://user-images.githubusercontent.com/28832235/38395747-ca1f8e80-3934-11e8-88fa-b6864de79aff.png)

One uses a squircle while the other one is a circle. Is this intentional? IMHO we should use the GTK version everywhere for more consistency.

**Comment by Feichtmeier** [comment]
@madsrh what's your opinion on that? Should both, shell and gtk, sliders use the same asset? :D

**Comment by madsrh** [comment]
IMO Let's go with consistency

![mockup](https://user-images.githubusercontent.com/3986894/38557709-26ee8692-3cce-11e8-82f1-0480b9ef906c.jpg)

**Comment by godlyranchdressing** [comment]
I'm worried that this might not be possible, but maybe someone else will know better. There's a custom Shell property called `-slider-handle-radius: 6px`, but all it seems to do is affect the actual size of the slider, _not_ the shape.

Example with 2px instead of 6px:
![example with 2px](https://user-images.githubusercontent.com/27529229/38877650-21cff66e-422d-11e8-9dc6-12d607d81ec4.png)

And any other "normal" CSS property under the `.slider ` class (which `-slider-handle-radius` falls under) affects the trough, not the slider. I tried digging through GNOME Shell's code and nothing stood out to me (in the past I found an unused CSS property so I was hoping I could get lucky).

**Comment by Feichtmeier** [comment]
In the end, if we accept that the shell is and can be different, many problems disappear. For example the shadow of pop ups and the popovers, these sliders here,  the dialogs (which was more my problem tbh). :)  But let's see maybe @godlyranchdressing is lucky. (I always wondered how that dressing tastes. Or is it actually from 👗? )

**Comment by Feichtmeier** [comment]
@Luxamman how about this for the GtkTheme sliders:
![image](https://user-images.githubusercontent.com/15329494/39209085-1a2b8ab2-4805-11e8-8635-e41c12ad9c82.png)

slider {
    $c: $neutral_color;
    @include button(normal, white);

    border: 1px solid _border_color($dark_fill);
    border-radius: 10px;

And this for the shell theme sliders:
![image](https://user-images.githubusercontent.com/15329494/39209351-ecad9b56-4805-11e8-810f-f0fbf7c5c044.png)

.slider {
  $_bg: $indication_bg_color; // $selected_bg_color;
  height: 1em;
  -slider-height: 0.1em;
  -slider-background-color: $dark_fill; // $osd_borders_color; //background of the trough
  -slider-border-color: $dark_fill; // $osd_borders_color; //trough border color
  -slider-active-background-color: $_bg; //active trough fill
  -slider-active-border-color: $_bg; //active trough border
  -slider-border-width: 1px;
  -slider-handle-radius: 8px;
}

**Comment by NusiNusi** [comment]
Maybe a tiny bit more contrast (darker border) for the slider in the gtk? For better visibility. But apart from that perfect.

**Comment by Luxamman** [comment]
Looking good in general, I would prefer the circles a little smaller - at least it looks a bit big on the screenshots. Thx ;)

**Comment by Feichtmeier** [comment]
Decreased the shell slider again. Sadly 100% consistency can't be achieved (maybe someone else can) because when I decrease the border radius in gtk it gets squircly again :disappointed: 
This is what I can do:
![screenshot from 2018-04-24 23-04-21](https://user-images.githubusercontent.com/15329494/39214208-fe06a7f4-4813-11e8-8064-097028758658.png)

**Comment by madsrh** [comment]
IMO let's merge them both and see what people think - LGTM

**Comment by Feichtmeier** [comment]
@madsrh alright merged both gtk and shell PRs. Try and if it works out for you close this issue and tag fixed
